apiVersion: v1
kind: ReplicationController
metadata:
  name: mybluemix-rc
  labels:
    user: root 
    app: mybluemix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: root
        app: mybluemix
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: contrasenia
          ports:
            - containerPort: 3306
        - name: mybluemix
          image: localhost:5000/mybluemix:latest
          imagePullPolicy: IfNotPresent 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: contrasenia
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mybluemix-svc
spec:
  ports:
    -
      port: 80
      targetPort: 80
  selector:
    user: root
    app: mybluemix
  type: LoadBalancer

# vim: si et sw=2 ts=2 syntax=yaml

