apiVersion: v1
kind: ReplicationController
metadata:
  name: mybluemix-rc
  labels:
    user: root 
    app: mybluemix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: root
        app: mybluemix
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: f00b4r # [0]
          ports:
            - containerPort: 3306
        - name: mybluemix
          image: localhost:5000/mybluemix:latest
          imagePullPolicy: IfNotPresent 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: f00b4r # [0]
          ports:
            - containerPort: 80

# [0]
# con kubernetes mas nuevos, puede ser:
#          valueFrom:
#            secretKeyRef:
#              name: my-secrets-store
#              key: mypass
#
# , previamente ejecutando:
#   $ kubectl create secret generic my-secrets-store --from-literal=mypass=f00b4r
#
---
apiVersion: v1
kind: Service
metadata:
  name: mybluemix-svc
spec:
  ports:
    -
      port: 80
      targetPort: 80
  selector:
    user: root
    app: mybluemix
  type: LoadBalancer

# vim: si et sw=2 ts=2 syntax=yaml

